collections:
  patterns:
    output: true
  antipatterns:
    output: true
  metapatterns:
    output: true
sass:
  style: compact
markdown: kramdown
kramdown:
  # Start Markdown headers at h3
  header_offset: 2
